app/main/animals/urls.py
from django.urls import path
from . import views

app_name = 'animals'

urlpatterns = [
    path("", views.home, name="home"),
    path("<int:pk>/", views.animal, name="animal"),
    path("create/", views.createAnimal, name="create"),
    path("update/<int:pk>/", views.updateAnimal, name="update"),
    path("delete/<int:pk>/", views.deleteAnimal, name="delete"),
]

app/main/base/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.loginPage, name="login"),
    path("logout/", views.logoutUser, name="logout"),
    path("register/", views.registerPage, name="register"),
    path("profile/<str:pk>/", views.userProfile, name="user-profile"),
]

app/main/main/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include

urlpatterns = [
    path('', include('base.urls')),
    path('animal/', include('animals.urls', namespace='animals')),
    path('samples/', include('samples.urls', namespace='samples')),
    path('owners/', include('owners.urls', namespace='owners')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('admin/', admin.site.urls),
] 

app/main/samples/urls.py
from django.urls import path
from . import views

app_name = 'samples'

urlpatterns = [
    path("", views.home, name="home"),
    path("<int:pk>/", views.sample, name="sample"),
    path("create/", views.createSample, name="create"),
    path("update/<int:pk>/", views.updateSample, name="update"),
    path("delete/<int:pk>/", views.deleteSample, name="delete"),
]

app/main/samples/models.py
from django.db import models
from animals.models import Animal
from django.conf import settings
from django.utils import timezone


class Type(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Sample(models.Model):
    name = models.CharField(max_length=150)
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True)
    sample_type = models.ForeignKey(
        Type, on_delete=models.SET_NULL, null=True, blank=True
    )
    collection_date = models.DateTimeField(default=timezone.now)
    analysis_results = models.TextField(null=True, blank=True)
    is_approved = models.BooleanField(default=False)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.DO_NOTHING,
        related_name="collected_samples",
    )
    created = models.DateTimeField(auto_now_add=True)
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="approved_samples",
    )
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated", "-created"]

    def __str__(self):
        return self.name

app/main/samples/forms.py
from django import forms
from django.forms import ModelForm
from .models import Sample

class SampleForm(ModelForm):
    class Meta:
        model = Sample
        fields = '__all__'
        exclude = ['created_by', 'updated_by']

app/main/samples/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from animals.models import Animal
from .models import Sample
from .forms import SampleForm
from base.decorators import check_user_permission


def home(request):
    q = request.GET.get("q") if request.GET.get("q") != None else ""

    samples = Sample.objects.filter(
        Q(id__icontains=q)
        | Q(name__icontains=q)
        | Q(sample_type__name__icontains=q)
        | Q(description__icontains=q)
        | Q(analysis_results__icontains=q)
    ).order_by("-created")

    context = {"samples": samples}
    return render(request, "samples/home.html", context)


def sample(request, pk):
    sample = Sample.objects.get(pk=pk)
    context = {"sample": sample}
    return render(request, "samples/sample.html", context)


@check_user_permission("samples.add_animal")
def createSample(request):
    form = SampleForm()
    if request.method == "POST":
        print(request.POST)
        form = SampleForm(request.POST)
        if form.is_valid():
            prepare = form.save(commit=False)
            prepare.created_by = request.user
            prepare.save()
            animal = Animal.objects.get(pk=prepare.animal.id)
            animal.operators.add(request.user)

            previous_page = request.META.get("HTTP_REFERER", "/")
            return redirect("animals:animal", pk=prepare.animal.id)
    context = {
        "title": "Create Sample",
        "method": "post",
        "action": reverse("samples:create"),
        "form": form,
    }
    return render(request, "base/components/form.html", context)


@check_user_permission("samples.change_animal")
def updateSample(request, pk):
    sample = Sample.objects.get(pk=pk)
    form = SampleForm(instance=sample)
    if request.method == "POST":
        form = SampleForm(request.POST, instance=sample)
        if form.is_valid():
            form.save()
            prepare = form.save(commit=False)
            prepare.updated_by = request.user
            prepare.save()
            return redirect("samples:sample", pk=prepare.id)
    context = {
        "title": "Edit Sample: " + sample.name,
        "method": "post",
        "action": reverse("samples:update", kwargs={"pk": pk}),
        "form": form,
    }
    return render(request, "base/components/form.html", context)


@check_user_permission("samples.delete_animal")
def deleteSample(request, pk):
    sample = Sample.objects.get(pk=pk)

    if request.method == "POST":
        sample.delete()
        return redirect("home")
    context = {"sample": sample}
    return render(request, "base/components/delete.html", {"obj": sample})

app/main/samples/templates/samples/components/samples_list.html
<div class="row">
    <div class="col-12">
        <div class="card overflow-auto shadow mb-4">
            <div class="card-body">
                <div class="card-header py-3 mb-3">
                    <h5 class="m-0 font-weight-bold">Samples list</h5>
                </div>
                <div class="table-responsive">
                    <table class="table table-bordered table-striped rounded"
                           id="dataTable"
                           width="100%"
                           cellspacing="0">
                        <thead class="text-center bg-light">
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Name</th>
                                <th scope="col">Type</th>
                                {% if animal is None %}<th>Animal name</th>{% endif %}
                                <th scope="col">Results</th>
                                <th scope="col">Description</th>
                                <th scope="col">Collected date</th>
                                <th scope="col">Status</th>
                                <th scope="col">&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for sample in samples %}
                                <tr>
                                    <th scope="row">{{ sample.id }}</th>
                                    <td>
                                        <a href="{% url 'samples:sample' sample.id %}">{{ sample.name|capfirst }}</a>
                                    </td>
                                    <td>{{ sample.sample_type }}</td>
                                    {% if animal is None %}
                                        <td>
                                            <a href="{% url 'animals:animal' sample.animal.id %}">{{ sample.animal }}</a>
                                        </td>
                                    {% endif %}
                                    <td>{{ sample.analysis_results|truncatewords:10 }}</td>
                                    <td>{{ sample.description|truncatewords:10 }}</td>
                                    <td>{{ sample.collection_date|date:'Y-m-d' }}</td>
                                    <td class="text-center">
                                        {% if sample.is_approved is True %}
                                            <span class="badge bg-success">Approved</span>
                                        {% else %}
                                            <span class="badge bg-danger">Not approved</span>
                                        {% endif %}
                                    </td>
                                    <td>
                                        <div class="nowrap">
                                            {% if perms.smaples.change_sample %}
                                                <a href="{% url 'samples:update' sample.id %}" class="m-1">
                                                    <i class="fa-solid fa-pen-to-square text-secondary"></i>
                                                </a>
                                            {% endif %}
                                            {% if perms.smaples.delete_sample %}
                                                <a href="{% url 'samples:delete' sample.id %}">
                                                    <i class="fa-solid fa-trash-can text-danger"></i>
                                                </a>
                                            {% endif %}
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>