app/main/animals/urls.py
from django.urls import path
from . import views

app_name = 'animals'

urlpatterns = [
    path("", views.home, name="home"),
    path("<int:pk>/", views.animal, name="animal"),
    path("create/", views.createAnimal, name="create"),
    path("update/<int:pk>/", views.updateAnimal, name="update"),
    path("delete/<int:pk>/", views.deleteAnimal, name="delete"),
]

app/main/base/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.loginPage, name="login"),
    path("logout/", views.logoutUser, name="logout"),
    path("register/", views.registerPage, name="register"),
    path("profile/<str:pk>/", views.userProfile, name="user-profile"),
]

app/main/main/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include

urlpatterns = [
    path('', include('base.urls')),
    path('animal/', include('animals.urls', namespace='animals')),
    path('samples/', include('samples.urls', namespace='samples')),
    path('owners/', include('owners.urls', namespace='owners')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('admin/', admin.site.urls),
] 

app/main/templates/footer.html
<footer id="footer" class="footer bg-white">
    <div class="copyright">
        VetPalApp 2024
    </div>
</footer>

app/main/templates/header.html
<header id="header" class="header fixed-top d-flex align-items-center">
    <div class="d-flex align-items-center justify-content-between">
        <a href="{% url 'home' %}" class="logo d-flex align-items-center">
            <i class="fa-solid fa-shield-dog"></i>
            <span class="d-none d-lg-block">VetPalApp</span>
        </a>
        <i class="fa-solid fa-bars"></i>
    </div>
    <div class="search-bar">
        <form class="search-form d-flex align-items-center" method="get" action="">
            <input type="text" name="q" value="{{ request.GET.q }}" placeholder="Search...." title="Enter search keyword" {{ request.GET.q|yesno:"autofocus," }}>
            <button type="submit" title="Search">
                <i class="fa-solid fa-magnifying-glass"></i>
            </button>
        </form>
    </div>
    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">
            <li class="nav-item d-block d-lg-none">
                <a class="nav-link nav-icon search-bar-toggle " href="#">
                    <i class="fa-solid fa-magnifying-glass bi bi-search"></i>
                </a>
            </li>
            <li class="nav-item dropdown pe-3">
                <a class="nav-link nav-profile d-flex align-items-center pe-0"
                   href="#"
                   data-bs-toggle="dropdown">
                    <i class="fa-solid fa-user rounded-circle"></i>
                    <span class="d-none d-md-block dropdown-toggle ps-2">{{ request.user.username }}</span>
                </a>
                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                    <li class="dropdown-header">
                        <h6>{{ request.user.username }}</h6>
                        <span>{{ request.user.email }}</span>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center"
                           href="{% url 'user-profile' request.user.id %}">
                            <i class="bi bi-person"></i>
                            <span>My Profile</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center"
                           href="{% url 'logout' %}">
                            <i class="bi bi-box-arrow-right"></i>
                            <span>Sign Out</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
</header>

app/main/templates/main.html
{% load bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="description" content="Your meta description goes here" />
    <meta name="keywords" content="your, meta, keywords, go, here" />
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}"
          rel="stylesheet"
          type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}"
          rel="stylesheet"
          type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}"
          rel="stylesheet"
          type="text/css">
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <link rel="icon" href="./favicon.ico" type="image/x-icon" />
    <title>VetPalApp</title>
  </head>
  <body>
    {% if user.is_authenticated %}
      <main id="main" class="main">
        {% include "header.html" %}
        {% include "sidebar.html" %}
        {% include "messages.html" %}
        {% block content %}
        {% endblock content %}
      </main>
    {% else %}
      {% include "messages.html" %}
      {% block login_register %}
      {% endblock login_register %}
    {% endif %}
  </body>
  {% if user.is_authenticated %}
    {% include "footer.html" %}
  {% endif %}
</html>

app/main/templates/messages.html
{% load bootstrap5 %}
{% if messages %}
  <div class="m-1 top-0 end-0">
    {% bootstrap_messages %}
  </div
{% endif %}

app/main/templates/sidebar.html
<aside id="sidebar" class="sidebar">
  <ul class="sidebar-nav" id="sidebar-nav">
    <li class="nav-item">
      <a class="nav-link collapsed" href="{% url 'home' %}">
        <i class="fa-solid fa-house"></i>
        <span>Home</span>
      </a>
    </li>
    <li class="nav-heading">Operations</li>
    <li class="nav-item">
      <a class="nav-link collapsed" href="{% url 'samples:create' %}">
        <i class="fa-solid fa-plus"></i><i class="fa-solid fa-vial"></i>
        <span>Add new sample</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link collapsed" href="{% url 'animals:create' %}">
        <i class="fa-solid fa-plus"></i><i class="fa-solid fa-dog"></i>
        <span>Add new animal</span>
      </a>
    </li>
    <li class="nav-heading">Pages</li>
    <li class="nav-item">
      <a class="nav-link collapsed" href="{% url 'animals:home' %}">
        <i class="fa-solid fa-dog"></i>
        <span>Animals list</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link collapsed" href="{% url 'samples:home' %}">
        <i class="fa-solid fa-vial"></i>
        <span>Samples list</span>
      </a>
    </li>
  </ul>
</aside>