app/main/animals/urls.py
from django.urls import path
from . import views

app_name = 'animals'

urlpatterns = [
    path("", views.home, name="home"),
    path("<int:pk>/", views.animal, name="animal"),
    path("create/", views.createAnimal, name="create"),
    path("update/<int:pk>/", views.updateAnimal, name="update"),
    path("delete/<int:pk>/", views.deleteAnimal, name="delete"),
]

app/main/base/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.loginPage, name="login"),
    path("logout/", views.logoutUser, name="logout"),
    path("register/", views.registerPage, name="register"),
    path("profile/<str:pk>/", views.userProfile, name="user-profile"),
]

app/main/main/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include

urlpatterns = [
    path('', include('base.urls')),
    path('animal/', include('animals.urls', namespace='animals')),
    path('samples/', include('samples.urls', namespace='samples')),
    path('owners/', include('owners.urls', namespace='owners')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('admin/', admin.site.urls),
] 

app/main/owners/urls.py
from django.urls import path
from . import views

app_name = 'owners'

urlpatterns = [
    path("<int:pk>/", views.ownerProfile, name="profile"),
]

app/main/base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from animals.models import Animal
from django.contrib.auth.models import Group, Permission


class VeterinarianUser(AbstractUser):
    is_veterinarian = models.BooleanField(default=False)

app/main/base/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import VeterinarianUser

class VeterinarianUserCreationForm(UserCreationForm):
    class Meta:
        model = VeterinarianUser
        fields = ['username', 'email'] 

app/main/base/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from animals.models import Animal, Owner
from samples.models import Sample
from django.contrib.auth import authenticate, login, logout
from .forms import VeterinarianUserCreationForm


def loginPage(request):
    page = "login"
    if request.user.is_authenticated:
        return redirect("home")

    if request.method == "POST":
        username = request.POST.get("username").lower()
        password = request.POST.get("password")

        try:
            user = get_user_model().objects.get(username=username)

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("home")
            else:
                messages.error(request, "Username OR password is incorrect")
        except:
            messages.error(request, "Username does not exist")

    context = {"page": page}
    return render(request, "base/login_register.html", context)


def logoutUser(request):
    logout(request)
    return redirect("login")


def registerPage(request):
    form = VeterinarianUserCreationForm()

    if request.method == "POST":
        form = VeterinarianUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)  # Don't save to database yet
            user.username = user.username.lower()
            user.save()
            login(request, user)

            return redirect("home")
        else:
            messages.error(request, "An error occurred during registration")

    context = {"form": form}
    return render(request, "base/login_register.html", context)


def home(request):
    q = request.GET.get("q") if request.GET.get("q") != None else ""

    animals = Animal.objects.filter(
        Q(id__icontains=q)
        | Q(owner__name__icontains=q)
        | Q(name__icontains=q)
        | Q(animal_type__name__icontains=q)
        | Q(description__icontains=q)
    )
    if q == "":
        animals = animals.order_by("-created")[0:25]

    owners = Owner.objects.filter(
        Q(name__icontains=q)
        | Q(id__icontains=q)
        | Q(phone_number__icontains=q)
        | Q(email__icontains=q)
    )
    recent_activities = []

    if request.user != None and request.user.is_authenticated:
        recent_activities = Sample.objects.filter(
            Q(animal__operators=request.user) | Q(created_by=request.user)
        ).order_by("-created")[0:5]

    context = {
        "animals": animals,
        "owners": owners,
        "recent_activities": recent_activities,
    }
    return render(request, "base/home.html", context)


def userProfile(request, pk):
    profile = get_user_model().objects.get(id=pk)

    operators_animals = Animal.objects.filter(operators=profile)
    own_animals = Animal.objects.filter(created_by=profile)
    animals = operators_animals | own_animals
    owners = Owner.objects.filter(animal__in=animals).distinct()
    samples = Sample.objects.filter(created_by=profile)
    recent_activities = Sample.objects.filter(created_by=profile).order_by("-created")[
        0:5
    ]

    context = {
        "profile": profile,
        "animals": animals,
        "samples": samples,
        "owners": owners,
        "recent_activities": recent_activities,
    }
    return render(request, "base/profile.html", context)

app/main/base/templates/base/components/delete.html
{% extends "main.html" %}
{% block content %}
  <div class="container-sm col-5">
    <div class="card">
      <div class="card-body">
        <div class="card-header py-3 mb-3">
          <h5 class="m-0 font-weight-bold">Delete confirmation</h5>
        </div>
        <h2>{{ obj }}</h2>
        <p>Are you sure you want to delete?</p>
      </div>
      <div class="card-footer text-center d-flex justify-content-around">
        <a href="{{ request.META.HTTP_REFERER }}">
          <button type="button" class="btn btn-primary">No and go back to previous page</button>
        </a>
        <form method="post" action="">
          <button type="submit" class="btn btn-danger">Yes I'd like to remove this entry</button>
          {% csrf_token %}
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

app/main/base/templates/base/components/form.html
{% extends "main.html" %}
{% load bootstrap5 %}
{% block content %}
  <div class="card">
    <div class="card-body">
      <div class="card-header py-3 mb-3">
        <h5 class="m-0 font-weight-bold">{{ title }}</h5>
      </div>
      <form method="{% if method|lower == 'post' %}post{% else %}get{% endif %}"
            action="{% if action is not Null %}{{ action }}{% endif %}">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="text-center">
          <button type="submit" class="btn btn-primary">Submit</button>
          <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
      </form>
    </div>
    <div class="card-footer">
      <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary">Back</a>
    </div>
  </div>
{% endblock content %}

app/main/base/templates/base/components/owners_list.html
<div class="card">
  <div class="card-body">
    <h5 class="card-title card-header mb-2">Recent active owners</h5>
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Phone</th>
          <th scope="col">Email</th>
        </tr>
      </thead>
      <tbody>
        {% for owner in owners %}
          <tr>
            <th scope="row">#{{ owner.id }}</th>
            <td>
              <a href="{% url 'owners:profile' owner.id %}?q={{ owner.name }}">{{ owner.name }}</a>
            </td>
            <td>{{ owner.phone_number }}</td>
            <td>{{ owner.email }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

app/main/base/templates/base/components/recent_activity.html
<div class="card">
  <div class="card-body">
    <h5 class="card-title card-header mb-2">Recent Activity</h5>
    <div class="activity">
      {% for activity in recent_activities %}
        <div class="activity-item d-flex">
          <div class="activite-label nowrap mx-1">{{ activity.created|date:"Y-m-d" }}</div>
          <i class="bi bi-circle-fill activity-badge text-success align-self-start"></i>
          <div class="activity-content">
            <a href="{% url 'animals:animal' activity.animal.id %}"
               class="fw-bold text-dark">{{ activity.animal }}</a>, {{ activity.name }} - {{ activity.description|truncatewords:8 }} <small class="text-muted ">{{ activity.created|timesince }}</small>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</div>