app/main/animals/urls.py
from django.urls import path
from . import views

app_name = 'animals'

urlpatterns = [
    path("", views.home, name="home"),
    path("<int:pk>/", views.animal, name="animal"),
    path("create/", views.createAnimal, name="create"),
    path("update/<int:pk>/", views.updateAnimal, name="update"),
    path("delete/<int:pk>/", views.deleteAnimal, name="delete"),
]

app/main/base/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.loginPage, name="login"),
    path("logout/", views.logoutUser, name="logout"),
    path("register/", views.registerPage, name="register"),
    path("profile/<str:pk>/", views.userProfile, name="user-profile"),
]

app/main/main/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include

urlpatterns = [
    path('', include('base.urls')),
    path('animal/', include('animals.urls', namespace='animals')),
    path('samples/', include('samples.urls', namespace='samples')),
    path('owners/', include('owners.urls', namespace='owners')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('admin/', admin.site.urls),
] 

app/main/owners/urls.py
from django.urls import path
from . import views

app_name = 'owners'

urlpatterns = [
    path("<int:pk>/", views.ownerProfile, name="profile"),
]

app/main/reports/urls.py
from django.urls import path
from .views import AnimalPDFView

app_name = 'reports'

urlpatterns = [
    path('<int:animal_id>', AnimalPDFView.as_view(), name='summary'),
]

app/main/animals/models.py
from django.db import models
from django.conf import settings
from owners.models import Owner


class Type(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Animal(models.Model):
    name = models.CharField(max_length=150)
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    operators = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="operators", blank=True
    )
    animal_type = models.ForeignKey(
        Type, on_delete=models.SET_NULL, null=True, blank=True
    )
    # image = models.ImageField(upload_to='animal_images/', null=True, blank=True)
    weight_kg = models.DecimalField(
        max_digits=5, decimal_places=2, null=True, blank=True
    )
    height_cm = models.PositiveIntegerField(null=True, blank=True)
    is_neutered = models.BooleanField(default=False)
    vaccination_records = models.TextField(null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.DO_NOTHING,
        related_name="created_animal",
    )
    created = models.DateTimeField(auto_now_add=True)
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.DO_NOTHING,
        null=True,
        blank=True,
        related_name="updated_animal",
    )
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated", "-created"]

    def __str__(self):
        return self.name

app/main/samples/models.py
from django.db import models
from animals.models import Animal
from django.conf import settings
from django.utils import timezone


class Type(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Sample(models.Model):
    name = models.CharField(max_length=150)
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True)
    sample_type = models.ForeignKey(
        Type, on_delete=models.SET_NULL, null=True, blank=True
    )
    collection_date = models.DateTimeField(default=timezone.now)
    analysis_results = models.TextField(null=True, blank=True)
    is_approved = models.BooleanField(default=False)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.DO_NOTHING,
        related_name="collected_samples",
    )
    created = models.DateTimeField(auto_now_add=True)
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="approved_samples",
    )
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated", "-created"]

    def __str__(self):
        return self.name

app/main/animals/forms.py
from django.forms import ModelForm
from .models import Animal

class AnimalForm(ModelForm):
    class Meta:
        model = Animal
        fields = '__all__'
        exclude = ['created_by', 'updated_by', 'operators']

app/main/animals/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required, permission_required
from base.decorators import check_user_permission
from django.db.models import Q
from .models import Animal
from .forms import AnimalForm
from samples.forms import SampleForm
from django import forms


def home(request):
    q = request.GET.get("q") if request.GET.get("q") != None else ""

    animals = Animal.objects.filter(
        Q(id__icontains=q)
        | Q(owner__name__icontains=q)
        | Q(name__icontains=q)
        | Q(animal_type__name__icontains=q)
        | Q(notes__icontains=q)
        | Q(description__icontains=q)
    )

    context = {"animals": animals}
    return render(request, "animals/home.html", context)


def animal(request, pk):
    q = request.GET.get("q") if request.GET.get("q") != None else ""

    animal = Animal.objects.get(pk=pk)
    samples = animal.sample_set.filter(
        Q(id__icontains=q)
        | Q(name__icontains=q)
        | Q(sample_type__name__icontains=q)
        | Q(description__icontains=q)
        | Q(analysis_results__icontains=q)
    ).order_by("-created")

    sample_form = SampleForm()
    sample_form.fields["animal"].initial = animal
    sample_form.fields["animal"].widget = forms.HiddenInput()

    operators = animal.operators.all()

    context = {
        "animal": animal,
        "samples": samples,
        "operators": operators,
        "sample_form": sample_form,
    }
    return render(request, "animals/animal.html", context)


@check_user_permission("animals.add_animal")
def createAnimal(request):
    form = AnimalForm()
    if request.method == "POST":
        print(request.POST)
        form = AnimalForm(request.POST)
        if form.is_valid():
            prepare = form.save(commit=False)
            prepare.created_by = request.user
            prepare.save()
            return redirect("animals:animal", pk=prepare.id)
    context = {
        "title": "Create Animal",
        "method": "post",
        "action": reverse("animals:create"),
        "form": form,
    }
    return render(request, "base/components/form.html", context)


@check_user_permission("animals.change_animal")
def updateAnimal(request, pk):
    animal = Animal.objects.get(pk=pk)
    form = AnimalForm(instance=animal)
    if request.method == "POST":
        form = AnimalForm(request.POST, instance=animal)
        prepare = form.save(commit=False)
        prepare.updated_by = request.user
        prepare.save()
        return redirect("animals:animal", pk=prepare.id)
    context = {
        "title": "Edit Animal: " + animal.name,
        "method": "post",
        "action": reverse("animals:update", kwargs={"pk": pk}),
        "form": form,
    }
    return render(request, "base/components/form.html", context)


@check_user_permission("animals.delete_animal")
def deleteAnimal(request, pk):
    animal = Animal.objects.get(pk=pk)
    if request.method == "POST":
        animal.delete()
        return redirect("home")
    context = {"animal": animal}
    return render(request, "base/components/delete.html", {"obj": animal})

app/main/animals/templates/animals/animal.html
{% extends "main.html" %}
{% block content %}
    {% load bootstrap5 %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl">
                <div class="col-auto">
                    <div class="card shadow">
                        <div class="card-body row">
                            <div class="card-header py-3 mb-3">
                                <h5 class=" font-weight-bold">Animal datasheet</h5>
                            </div>
                            <div class="col-lg-2">
                                <div class="card">
                                    <div class="card-body pt-2 d-flex flex-column align-items-center rounded text-center shadow-sm">
                                        <div class="blank-profile-photo mt-2 mb-2 rounded light-bg">
                                            <i class="fa-solid fa-dog"></i>
                                            <br>
                                        </div>
                                        <h5 class="text-center">{{ animal.name|truncatewords:2 }}</h5>
                                        <h6 class="text-center text-muted">{{ animal.animal_type }}</h6>
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="tab-content pt-2">
                                    <div class="tab-pane fade show active profile-overview"
                                         id="profile-overview">
                                        <h5 class="card-title">About</h5>
                                        <p class="small fst-italic">{{ animal.description }}</p>
                                        <h5 class="card-title">Details</h5>
                                        <div class="row">
                                            <div class="col-lg-3 col-md-4 label">Veterinarian</div>
                                            <div class="col-lg-9 col-md-8">
                                                <a href="{% url 'user-profile' animal.created_by.id %}"
                                                   title="Jump to {{ animal.created_by.first_name }} profile">{{ animal.created_by.first_name }} {{ animal.created_by.last_name }}
                                                </a>
                                            </div>
                                        </div>
                                        <div class="row">&nbsp;</div>
                                        <div class="row">
                                            <div class="col-lg-3 col-md-4 label ">Full Name</div>
                                            <div class="col-lg-9 col-md-8">{{ animal.name }}</div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-3 col-md-4 label">Owner name</div>
                                            <div class="col-lg-9 col-md-8">
                                                <a href="{% url 'owners:profile' animal.owner.id %}"
                                                   title="Jump to {{ animal.owner }} profile">{{ animal.owner }}</a>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-3 col-md-4 label">Birth Date</div>
                                            <div class="col-lg-9 col-md-8">{{ animal.birth_date|date:"d-m-Y" }}</div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-3 col-md-4 label">Weight</div>
                                            <div class="col-lg-9 col-md-8">
                                                {{ animal.weight_kg }} <small>kg</small>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-3 col-md-4 label">Birth Date</div>
                                            <div class="col-lg-9 col-md-8">
                                                {{ animal.height_cm }} <small>cm</small>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-3 col-md-4 label">Neutered</div>
                                            <div class="col-lg-9 col-md-8">
                                                <input type="checkbox"
                                                       class="checkbox"
                                                       onclick="return(false)"
                                                       {% if animal.is_neutered is True %}checked{% endif %}>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-3 col-md-4 label">Notes</div>
                                            <div class="col-lg-9 col-md-8">{{ animal.notes }}</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <div class="row align-right">
                                {% if request.user.is_veterinarian %}
                                    <div class="col-auto">
                                        <a href="{% url 'reports:summary' animal.id %}"
                                           download
                                           class="btn btn-secondary btn-sm"><i class="fa-solid fa-clipboard-list"></i> Download summary</a>
                                    </div>
                                {% endif %}
                                {% if perms.animals.change_animal %}
                                    <div class="col-auto">
                                        <a href="{% url 'animals:update' animal.id %}"
                                           class="btn btn-primary btn-sm"><i class="fa-solid fa-pencil"></i> Edit</a>
                                    </div>
                                {% endif %}
                                {% if perms.animals.delete_animal %}
                                    <div class="col-auto">
                                        <a href="{% url 'animals:delete' animal.id %}"
                                           class="btn btn-danger btn-sm"><i class="fa-solid fa-trash"></i> Delete</a>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-auto">{% include "samples/components/samples_list.html" with animal=animal %}</div>
            </div>
            <div class="col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <div class="card-header py-3 mb-3">
                            <h5 class="m-0 font-weight-bold">Operators</h5>
                        </div>
                        <ul class="list-group">
                            {% for operator in operators %}
                                <a href="{% url 'user-profile' operator.id %}"
                                   title="Jump to {{ operator }} profile">
                                    <li class="list-group-item {% if request.user == operator %}active{% endif %}">{{ operator }}</li>
                                </a>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                {% if perms.samples.add_sample %}
                    <div class="card shadow">
                        <div class="card-body">
                            <div class="card-header py-3 mb-3">
                                <h5 class="m-0 font-weight-bold">Add new sapmle</h5>
                            </div>
                            <form method="post" action="{% url 'samples:create' %}">
                                {% csrf_token %}
                                {% bootstrap_form sample_form %}
                                <div class="row mb-3">
                                    <div class="col-sm-10">
                                        <button type="submit" class="btn btn-primary">Submit Form</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

app/main/animals/templates/animals/home.html
{% extends "main.html" %}
{% block content %}
    <div class="pagetitle">
        <h1>Dashboard</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'home' %}">Home</a>
                </li>
                <li class="breadcrumb-item active">Animals list</li>
            </ol>
        </nav>
    </div>
    <section class="section dashboard">
        {% include "animals/components/animals_list.html" %}
    </section>
{% endblock content %}